name: hadoop_lab

services:
  namenode:
    build: .
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      HADOOP_HOME: "/opt/hadoop"
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HDFS_NAMENODE_OPTS: "-XX:+UseSerialGC -Xmx2g"
      HADOOP_USER_NAME: paul
    volumes:
      - ./data/:/data
    networks:
      - hdnet


  resourcemanager:
    build:
      dockerfile: Dockerfile-resourcemanager
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    hostname: resourcemanager
    ports:
      - 8088:8088
      - 19888:19888
    environment:
      HADOOP_HOME: "/opt/hadoop"
    networks:
      - hdnet

  datanode:
    build:
      dockerfile: Dockerfile-datanode
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      HADOOP_HOME: "/opt/hadoop"
      YARN_NODEMANAGER_OPTS: "-XX:+UseSerialGC -Xmx2g"
    networks:
      - hdnet

networks:
  hdnet: