FROM eclipse-temurin:8-jre-alpine

ARG JAR_FILE="./build/libs/hadoop-test-1.0-SNAPSHOT.jar"

ENV APP_NAME="app.jar"

COPY ${JAR_FILE} ${APP_NAME}

RUN adduser -D hadoop

USER hadoop

ENTRYPOINT ["sh", "-c", "java -jar /${APP_NAME}"]