services:

  namenode:
    build: .
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8080:8080
      - 8020:8020
    environment:
      HADOOP_HOME: "/opt/hadoop"
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HDFS_NAMENODE_OPTS: "-XX:+UseParallelGC -Xmx2g"
      HADOOP_USER_NAME: paul
    volumes:
      - ./data/:/data
    networks:
      - hdnet


  resourcemanager:
    build:
      dockerfile: Dockerfile-resourcemanager
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    hostname: resourcemanager
    ports:
      - 8088:8088
      - 19888:19888
      - 8032:8032
    environment:
      HADOOP_HOME: "/opt/hadoop"
    networks:
      - hdnet

  #    volumes:
#      - ./test.sh:/opt/test.sh

  datanode-1:
    build:
      dockerfile: Dockerfile-datanode
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      HADOOP_HOME: "/opt/hadoop"
      YARN_NODEMANAGER_OPTS: "-XX:+UseParallelGC -Xmx2g"
    networks:
      - hdnet

  datanode-2:
    build:
      dockerfile: Dockerfile-datanode
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      HADOOP_HOME: "/opt/hadoop"
      YARN_NODEMANAGER_OPTS: "-XX:+UseParallelGC -Xmx2g"
    networks:
      - hdnet

  datanode-3:
    build:
      dockerfile: Dockerfile-datanode
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      HADOOP_HOME: "/opt/hadoop"
      YARN_NODEMANAGER_OPTS: "-XX:+UseParallelGC -Xmx2g"
    networks:
      - hdnet

networks:
  hdnet: